widget:
  membership:
    begins:
      salutation: "Welcome to the Players Club."
      opening:    "Welcome to the game of your life!"
      situation:  "We are excited you decided to play with us.  Life is a game that is more fun when we all play together."
      message:    "Here is your temporary password to login when you return: **<%= @password %>**"
      invitation: "And here is the link to return to the Players Club: <ENV['PLAYERS_CLUB_URL']>"
      reminder:   "You can always reset this password if you wish by simply following the Reset Password link under the Returning Players login."
      conclusion: "And remember to live your life like it's your favorite game to play!"
      sign_off: |
        with love,
        Your Players Club Team
players_club:
  delinquent:
    missed:
      salutation: "Hi there and thanks for joining us in the Life Elevated Players Club."
      opening:    "We want to let you know that we've encountered a problem trying to charge the Credit Card you listed for payment."
      situation:  "We were unable to process the Credit Card Number as entered."
      message:    "And because we know you want to find out what's in the cards for you, we encourage you to return to the Players Club and re-enter your Credit Card information so that you can play your cards right each and every day."
      invitation: "Here's the link: <ENV['PLAYERS_CLUB_URL']>"
      conclusion: "See you back in the game."
      sign_off: |
        with love,
        Your Players Club Team
    unresolved:
      salutation: "Hi there, and thanks again for joining us in the Life Elevated Players Club."
      opening:    "A few days ago we encountered a problem trying to charge your Credit Card."
      message:    "And because we know how much you value clarity and because we know you're commmitted to playing your cards right, we want to ensure you have uninterrupted access to the Players Club."
      invitation: "So please click here to update your Credit Card information: <ENV['PLAYERS_CLUB_URL']>"
      conclusion: "See you back in the game."
      sign_off: |
        with love,
        Your Players Club Team
    late:
      salutation: "Hi there, from your Players Club team."
      opening:    "We want to let you know that last week we encountered a problem trying to charge your Credit Card."
      message:    "And because we know how much you value clarity and because we know you're commmitted to playing your cards right, we want to ensure you have uninterrupted access to the Players Club. So, please update your card information, or unfortunately you'll lose access to the Players Club."
      invitation: "Click here to update your Credit Card information: <ENV['PLAYERS_CLUB_URL']>"
      conclusion: "See you back in the game."
      sign_off: |
        with love,
        Your Players Club Team
    over:
      salutation: "Hi there, from your Players Club team"
      opening:    "We want to let you know that we have encountered a problem trying to charge your Credit Card. And this is our third email to you."
      message:    "Because we know how much you value clarity and because we know you're commmitted to playing your cards right, we want to ensure you have uninterrupted access to the Players Club."
      conclusion: "So, you have 48 hous to update your Credit Card information or else your access to the Players Club will be curtailed."
      invitation: "Click here to update your Credit Card information: <ENV['PLAYERS_CLUB_URL']>"
      sign_off: |
        with love,
        Your Players Club Team
