member_form:
  header: "Join The Players Club for FREE"
  subheader: "It's FREE"
  description: |
    Look up your cards to play. And look up other people's cards too!

    Create your FREE Player Profile.

    - You'll receive a temporary password and other important information emailed to you. So please make sure to provide a valid email you check regularly. 

  instructions: "Create Your FREE Player Profile"
  privacy_policy: |
    Policy for Free Members: Your email address is safe with us. We will never share it with anyone. And you may always opt out of emails or unsubscribe at a later date if you wish.

password:
  incorrect: |
    Oops, it looks like you're entering the wrong password.<br>
    The temporary password is 'ENV['INITIAL_PASSWORD']'.<br>
    You can also reset your password via the link below.

subscription:
  teaser:
    header: See More Cards
    subheader: Become a member
    offer: |
      For $ENV['MONTHLY_PRICE'] per month, you will discover

      * Your upcoming Yearly Card, so you can see what's coming.
      * Last year's Yearly Card, so you can review important life lessons.
      * Your upcoming 52-Day Card, so you can plan accordingly.
      * Your previous 52-Day Card, so you can process what just happened.
      * The planetary meaning of your 52-Day Cycle.
      * The exact date your 52-Day Card will change...
      * Your personal Daily Card for each and every day.
      * Now you can also see Yesterday's Daily Card plus Tomorrow's Daily Card to plan your days accordingly!

      Cool huh?
    accept: Yes, begin my FREE 7-day trial.
    defer: No, this is enough for now.
  checkout:
    submit: Yes, I'm ready to learn more!
  transaction:
    succeeded_first: "Thank you for becoming a member!  Your card for today is the "
    succeeded_second: ".  You can also look into the future at your upcoming cards (refresh this page)."
    failed: Your transaction was not completed.  This may be due to bank security measures, which are very tight these days.  If you use a different payment method or contact your bank, perhaps the next attempt will succeed.
    past_due: "Uh Oh! There was a problem with your Players Club subscription!"
  upgrade:
    succeeded: "Wonderful choice.  Join us in the Salon at ENV['PLAYERS_CLUB_SALON_URL'] .  The address has been emailed to you."
  update:
    initiate: "I would like to update my payment method."
    accept: "Do you need to update your payment information?"
    submit: "Update my payment."
    succeeded: "Thank you."
    failed: "That payment method was not finalized."
  unsubscribe:
    link: I am ready to end my subscription.
    confirm: Are you sure you wish to end your subscription?
  cancellation:
    policy: "Policy for Premium Users: Once you enter your Credit Card information, you begin a 7-day introductory free trial of your Premium Membership. After the trial period, you will be billed $ENV['MONTHLY_PRICE'] automatically each month. We keep all your information strictly private. We do not share your information with any third parties. You may cancel your subscription at any time, including during the 7-day introductory free Premium trial."

book:
  question: "Want to learn more?"
  answer: "Get the book."

coaching:
  question: Want to learn more?
  answer: Ask Alexander

new_players:
  header: "New Players"
  subheader: "Find Out Your Birth Card"
  instructions: "Enter your Date of Birth:"
  button: "Go"
returning_players:
  header: "Returning Players"
  subheader: "Login to get back in the game:"
  instructions: "A temporary password was emailed to you."
  password_hint: "The temporary password is 'ENV['INITIAL_PASSWORD']'"
  button: "Get Back In The Game"
  email_name: "Profile Email"
  password_name: "Password"
  remember_name: "By checking this box, you'll stay logged in and have easy access when you return."
  reset_name: "Reset Password"
new_teammates:
  subheader: "Look Up Someone Else's Cards"
  instructions: "Enter their Date of Birth"

navigation:
  lookup: 'Birth Card Lookup'
  reading: 'My Reading'
  log_out: 'Log Out'

heading:
  member:
    birth:
      header: "Your Birth Card"
    personality:
      header: "Your Personality Card"
      subheader: 
    yearly:
      header_last: "Last Yearly Card"
      header: "Your Yearly Card"
      header_next: "Coming Yearly Card"
      subheader: "This card represents the main theme of your year. Your year starts from your last birthday until your next birthday."
    planetary:
      header_last: "Previous 52-Day Card"
      header: "Your 52-Day Card"
      header_next: "Coming 52-Day Card"
      subheader: "This card represents a specific energy pattern in play for this 52-day cycle, "
    daily:
      header: "Today's Card"
      subheader: "This card will be with you until midnight."
    tomorrow:
      header: "Tomorrow's Card"
      subheader: "This card will join you at midnight."
    yesterday:
      header: "Yesterday's Card"
      subheader: "This card was with you yesterday."
    cinderella:
      header: "Today's Card"
      subheader: "This card has been with you since midnight."
  acquaintance:
    birth:
      header: "Their Birth Card"
    personality:
      header: "Their Personality Card"
      subheader: 
    yearly:
      header_last: "Last Yearly Card"
      header: "Their Yearly Card"
      header_next: "Coming Yearly Card"
      subheader: "This card represents the main theme of the year. Your year is from your last birthday until your next birthday."
    planetary:
      header_last: "Previous 52-Day Card"
      header: "Their 52-Day Card"
      header_next: "Coming 52-Day Card"
      subheader: "This card represents the current period of their year. It indicates a specific energy pattern in play for this 52-day cycle."

button:
  member:
    birth:
      button_current: "My Birth Card"
    personality:
      button: "Jump Over the Cusp"
    yearly:
      button_last: "See Last Year's Card"
      button_current: "See This Year's Card"
      button_next: "See Next Year's Card"
    planetary:
      button_last: "See Your Previous Card"
      button_current: "See Your Current Card"
      button_next: "See Your Next Card"
    daily:
      button_current: "My Card for Today"
  acquaintance:
    personality:
      button: "Jump Over the Cusp"
    yearly:
      button_last: See Last Year's Card
      button_current: "See This Year's Card"
    planetary:
      button_last: "See Their Previous Card"
      button_current: "See Their Current Card"

preview:
  personality:
    description: |
      Your Personality Card is the second most important card in your life. You may even be more identified with it than your Birth Card. It’s how you show up in your world. 

      <strong class='joining_players_club'>Join the Players Club</strong> to find out your Personality Card.  It's FREE to join.
  yearly:
    description: |
      Starting on our Birthday, we have new cards to play each year. Based on which cards are in play, we have specific challenges to resolve and specific opportunities for growth. 

      <strong class='joining_players_club'>Join the Players Club</strong> to find out the card that indicates the central theme of your life this year.  It's FREE to join.
  planetary:
    description: |
      During our year, from Birthday to Birthday, we move through seven specific cycles of influence. Each cycle in the year is 52 days long. 

      <strong class='joining_players_club'>Join the Players Club</strong> to find out which card is in play for you right now during this cycle, so you can clarify what’s happening for you right now.  It's FREE to join.
      
cusp:
  member:
    personality:
      cusp_picker: "Your birthday is on an astrological cusp. To correctly determine your Personality Card, we need to know which is your Western Astrological sign. If you know it, please click it here:"
      cusp_unsure: "If you are unsure of your Astrological Birth Sign, you may"
      cusp_unsure_two: "with the time and place of your birth, and we will look it up for you. We will respond to your email in about 24 hours. Alternately, there are free lookup tools on the web for you to look up your Astrological sign. And, if you want, you can play with each Astrological Sign option to see which Personality Card appears. A button will link you back to this page to change your choice again."
      
  acquaintance:
    personality:
      cusp_picker: "This birthday is on an astrological cusp. To correctly determine the Personality Card, we need to know which is their Western Astrological sign. If you know it, please click it here:"
      cusp_unsure: "If you are unsure of their Astrological Birth Sign, you may"
      cusp_unsure_two: "with the time and place of their birth, and we will look it up for you. We will respond to your email in about 24 hours. Alternately, there are free lookup tools on the web for you to look up an Astrological sign. And, if you want, you can play with each Astrological Sign option to see which Personality Card appears. A button will link you back to this page to change your choice again."
