new_players:
  header: "Source Card Lookup"
  instructions: |
    Put in Your Birth Date. Then Click Enter.
  button: "Enter"
  invitation: "Click on each Card to discover the game of your life."

card_reading:
  birth_card:
    identification: "Your Birth Card is the"
    symbolizing: "This pattern symbolizes the fundamental experience of your life."
    instructions: "Click the Card to learn more."
  personality_card:
    identification: "Your Personality Card is the"
    symbolizing: "This pattern symbolizes the identity that may define you."
    instructions: "Click the Card to learn more."
  birthday_card:
    identification: "For the birthday of"
    instructions: "To discover more about your birthday, click above on your Birthday Card"
