new_players:
  header: "Source Card Lookup"
  instructions: |
    Select Your Birth Date. Then Click Enter.
  button: "Enter"
  invitation: "Click on each card to read the game of your life."

card_reading:
  birth_card:
    identification: "Your Birth Card is the"
    symbolizing: "This pattern symbolizes the fundamental experience of your life."
    instructions: "Click the Card to learn more."
  personality_card:
    identification: "Your Personality (Ruling) Card is the"
    symbolizing: "This pattern symbolizes the identity that may define you."
    instructions: "Click the Card to learn more."
    cusp: "Your birthday is on an astrological cusp. Do you know which one is your sign?"
  birthday_card:
    identification: "For the birthday of"
    instructions: "To learn more about the patterns of your birthday and to get inspiration for your life, click above on your Birthday Card."

navigation:
  another_lookup: "Look Up Another Birthday"
